### ISSUE TITLE
Investigate issue with the old DVL

### ISSUE THREAD

**Issue by poornack** [uvic-auvic/Hardware-Tasks#18]
**Problem Description:** We have an old Doppler Velocity Log from a years ago. It doesn't work, but no one knows why. It would be really nice get that working again.

**Task:** Investigate why the DVL isn't working and determine if it is feasible to get it working again.

**Comment by poornack** [comment]
You want me to make like a word doc explaining how to use it or would just posting the procedure here be good enough?

**Comment by anijjar** [comment]
You want me to make like a word doc explaining how to use it or would just posting the procedure here be good enough?

**Comment by poornack** [comment]
It would be nice to have a document once we verify that everything works. For now, just post your findings here. What you've done so far and what you plan on doing next. Next step should be to test if it can return velocity values. We can do what we did with the sub last semester where we put it on the blue cart and pushed it down the hallway.

**Comment by anijjar** [comment]
1 - soldered female ports onto a serial-usb converter to access the memory.
2 - downloaded and ran bbtalk software to reset the device to factory settings
3 - Set Baud Rate to 9600
4 - configured DVL Control Flow Register for manual ensemble/ping cycle, hex-ASCII output, enabled Serial output, and Disabled Data Recorder.
5 - The receiving Data is currently unreadable, However previous team used only 1 TX/RX pins so either it will work with only 1, or they are incompetent such that they could not get store-bought hardware to work :).

**Comment by anijjar** [comment]
There are 3 different Data Streaming formats. We don't have to request data from all functions, thereby saving reducing memory and power cost by disabling unneeded hardware. A potential high-level Firmware task could be to chose one output format and write an appropriate decoder.  

PD0 – PD0 is Teledyne RD Instrument’s standard format. PD0 is a binary
output format. It provides the most information possible including
a header, fixed and variable leader, bottom track, and water profile information.
The fixed and variable leader is a recording of time, ADCP
setup, orientation, heading, pitch, roll, temperature, pressure, and self
test diagnostic results. Data fields to be output are user selectable.
• PD4 – PD4 is a binary output format of bottom track speed over the bottom,
speed through the water, and range to bottom information.
• PD5 – PD5 is a superset of PD4 and includes information on salinity,
depth, pitch, roll, heading, and distance made good.

![capture](https://user-images.githubusercontent.com/26446969/46177195-ce655400-c266-11e8-96f3-ca1b1002b5aa.PNG)
